//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication3.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Erasmus+ (Erasmus Plus), Avrupa Birliği tarafından eğitim, iş deneyimi ve sportif aktivite gibi alanlarda kişilerin kendilerini geliştirmeleri için hazırlanmış bir programdır.
        ///                Erasmus, üniversite ve yüksek lisans öğrencilerinin ve eğitim görevlilerinin eğitimlerine yurtdışındaki bir üniversitede devam etmelerini sağlamaları ve yeni iş olanakları elde edebilmeleri amacıyla kurulmuş bir sistemdir.
        ///                Erasmus öğrenim hareketliliği staj hareketliliği ve personel hareketliliği diye [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AnasayfaP1 {
            get {
                return ResourceManager.GetString("AnasayfaP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erasmus Nedir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ErasmusNedir {
            get {
                return ResourceManager.GetString("ErasmusNedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erasmus Şartları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ErasmusŞartları {
            get {
                return ResourceManager.GetString("ErasmusŞartları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erasmus+ (Erasmus Plus) programı ile üniversite değişim programlarına katılmak ya da yurtdışında staj yapmak isteyenlerin belirli şartları yerine getirmesi gerekmektedir.
        ///                Bu program ile yurtdışına çıkmak isteyen öğrenciler, başvurdukları dönemde bir üniversiteye kayıtlı olmalılardır.
        ///                Birçok üniversite öğrenciler için yurtdışında eğitim görmeden önce en az iki dönem üniversite eğitimi görmüş olmalarını istemektedir.
        ///                Buna ek olarak, alacağınız dersleri anlama [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ErasmusŞartlarıP1 {
            get {
                return ResourceManager.GetString("ErasmusŞartlarıP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erasmus öğrenim hareketliliği en basit haliyle, bir yükseköğretim öğrencisinin (üniversite öğrencisi) eğitim gördüğü
        ///                                                        Türkiye’deki üniversitenin (Sending Institution) Erasmus anlaşması olan Avrupa’daki bir üniversiteye (Receiving Institution)
        ///                                                        1 ya da 2 dönem olacak şekilde herhangi bir ücret ödemeden eğitim görmeye gitmesidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ErasmusŞartP2 {
            get {
                return ResourceManager.GetString("ErasmusŞartP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Öğrenim Hareketliliği benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÖğrenimHareketliliği {
            get {
                return ResourceManager.GetString("ÖğrenimHareketliliği", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Staj Hareketliliği benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StajHareketliliği {
            get {
                return ResourceManager.GetString("StajHareketliliği", resourceCulture);
            }
        }
    }
}
