//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Kaydol {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Kaydol() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication3.Resources.Kaydol", typeof(Kaydol).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Adı {
            get {
                return ResourceManager.GetString("Adı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bolum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Bolum {
            get {
                return ResourceManager.GetString("Bolum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Eposta {
            get {
                return ResourceManager.GetString("Eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gidilecek Sehir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GidilecekSehir {
            get {
                return ResourceManager.GetString("GidilecekSehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gidilecek Üniversite benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GidilecekÜniversite {
            get {
                return ResourceManager.GetString("GidilecekÜniversite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KaydolSekme {
            get {
                return ResourceManager.GetString("KaydolSekme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Parola {
            get {
                return ResourceManager.GetString("Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parolanızı onaylayın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Parolayıonaylayın {
            get {
                return ResourceManager.GetString("Parolayıonaylayın", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Soyadı {
            get {
                return ResourceManager.GetString("Soyadı", resourceCulture);
            }
        }
    }
}
