//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KonakModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KonakModel() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication3.Resources.KonakModel", typeof(KonakModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Fiyat {
            get {
                return ResourceManager.GetString("Fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaç Odalı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KaçOdalı {
            get {
                return ResourceManager.GetString("KaçOdalı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kisi Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KisiSayısı {
            get {
                return ResourceManager.GetString("KisiSayısı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kız / Erkek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KızErkek {
            get {
                return ResourceManager.GetString("KızErkek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sehirler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Sehirler {
            get {
                return ResourceManager.GetString("Sehirler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yakın / Uzak benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YakınUzak {
            get {
                return ResourceManager.GetString("YakınUzak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yurt / Ev benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YurtEv {
            get {
                return ResourceManager.GetString("YurtEv", resourceCulture);
            }
        }
    }
}
